CREATE TABLE `user`(
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  NAME VARCHAR(18) NOT NULL COMMENT '姓名',
  age INT(11) DEFAULT '0' COMMENT '年龄',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;